[package]
name = "eth_crypt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ecies = "0.2"
secp256k1 = "0.20"
hex = "0.4"
clap = {version = "4", features = ["derive"]}